# Generated by Django 5.1.4 on 2025-01-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('claim_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('audit_date', models.DateTimeField(null=True)),
                ('claim_owner_first_name', models.CharField(max_length=100, null=True)),
                ('claim_owner_last_name', models.CharField(max_length=100, null=True)),
                ('claim_status', models.CharField(max_length=50, null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('general_nature_of_loss', models.CharField(max_length=255, null=True)),
                ('lob', models.CharField(max_length=100, null=True)),
                ('location_state', models.CharField(max_length=100, null=True)),
                ('loss_claim_cause', models.CharField(max_length=255, null=True)),
                ('loss_date', models.DateTimeField(null=True)),
                ('policy_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='ClaimAuditable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_id', models.CharField(max_length=20)),
                ('parameter_score', models.CharField(max_length=20, null=True)),
                ('parameter_score_ai', models.CharField(max_length=20, null=True)),
                ('audit_date', models.DateTimeField(null=True)),
                ('parameter_name', models.CharField(max_length=100, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('final_audit_status', models.CharField(max_length=100, null=True)),
                ('parameter_audit_date', models.DateTimeField(null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='backend_app.claims')),
            ],
            options={
                'db_table': 'claim_auditable',
            },
        ),
    ]
