# Generated by Django 5.1.4 on 2025-01-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('operationalised_flag', models.CharField(max_length=10, null=True)),
                ('operationalised_status', models.CharField(max_length=100, null=True)),
                ('other_subparameter_id', models.CharField(max_length=100, null=True)),
                ('subtype_name', models.CharField(max_length=100, null=True)),
                ('type_code', models.CharField(max_length=100, null=True)),
                ('type_end_date', models.DateTimeField(null=True)),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('type_start_date', models.DateTimeField(null=True)),
                ('type_status', models.CharField(max_length=100, null=True)),
                ('type_value', models.CharField(max_length=100, null=True)),
                ('compliance_flag', models.CharField(max_length=10, null=True)),
                ('component_of_claim', models.CharField(max_length=100, null=True)),
                ('customer_experience_flag', models.CharField(max_length=10, null=True)),
                ('data_integrity_flag', models.CharField(max_length=10, null=True)),
                ('leakage_flag', models.CharField(max_length=10, null=True)),
                ('indicator_name', models.CharField(max_length=255, null=True)),
                ('line_of_business', models.CharField(max_length=255, null=True)),
                ('parameter_end_date', models.DateTimeField(null=True)),
                ('parameter_no', models.IntegerField(null=True)),
                ('parameter_stage', models.CharField(max_length=100, null=True)),
                ('parameter_start_date', models.DateTimeField(null=True)),
                ('parameter_status', models.CharField(max_length=100, null=True)),
                ('parameter_type', models.CharField(max_length=100, null=True)),
                ('parameter_weightage', models.IntegerField(null=True)),
                ('phase_name', models.CharField(max_length=100, null=True)),
                ('policy_review_flag', models.CharField(max_length=10, null=True)),
                ('question', models.TextField(null=True)),
                ('sampling_methodology', models.CharField(max_length=100, null=True)),
                ('signal_id', models.CharField(max_length=100, null=True)),
                ('signal_level', models.CharField(max_length=100, null=True)),
                ('source_system', models.CharField(max_length=100, null=True)),
                ('triggers', models.CharField(max_length=100, null=True)),
                ('unit_of_measurement', models.CharField(max_length=100, null=True)),
                ('subparameter_description', models.TextField(null=True)),
                ('subparameter_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
