# Generated by Django 5.1.4 on 2025-01-02 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('complaint_id', models.CharField(max_length=100, null=True)),
                ('policy_id', models.CharField(max_length=100, null=True)),
                ('action_needed_flag', models.CharField(max_length=10, null=True)),
                ('ai_signal', models.CharField(max_length=100, null=True)),
                ('assigned_by', models.CharField(max_length=100, null=True)),
                ('assigned_date', models.DateTimeField(null=True)),
                ('assigned_userid', models.CharField(max_length=100, null=True)),
                ('claim_stage', models.CharField(max_length=100, null=True)),
                ('claim_status', models.CharField(max_length=100, null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('comments', models.TextField(null=True)),
                ('confidence_score', models.FloatField(null=True)),
                ('consultant_name', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('current_status', models.CharField(max_length=100, null=True)),
                ('dsoutcome_key_retrigger', models.CharField(max_length=100, null=True)),
                ('exposure_details', models.TextField(null=True)),
                ('exposure_id', models.CharField(max_length=100, null=True)),
                ('final_leakage_amount', models.FloatField(null=True)),
                ('final_signal', models.CharField(max_length=100, null=True)),
                ('indicator_value', models.CharField(max_length=100, null=True)),
                ('indicator_name', models.CharField(max_length=255, null=True)),
                ('indicator_percentage', models.FloatField(null=True)),
                ('is_broker', models.BooleanField(null=True)),
                ('isdeleted', models.BooleanField(null=True)),
                ('isvalidated', models.BooleanField(null=True)),
                ('leakage_level', models.CharField(max_length=100, null=True)),
                ('leakage_type', models.CharField(max_length=100, null=True)),
                ('manual_signal', models.CharField(max_length=100, null=True)),
                ('manual_leakage_amount', models.FloatField(null=True)),
                ('month_begin', models.DateTimeField(null=True)),
                ('notification_status', models.CharField(max_length=100, null=True)),
                ('notification_comment', models.TextField(null=True)),
                ('parameter_name', models.CharField(max_length=100, null=True)),
                ('parameter_stage', models.CharField(max_length=100, null=True)),
                ('payset_id', models.CharField(max_length=100, null=True)),
                ('potential_leakage_amount', models.FloatField(null=True)),
                ('recommended_action', models.TextField(null=True)),
                ('reconsider_age', models.IntegerField(null=True)),
                ('reconsideration_date', models.DateTimeField(null=True)),
                ('reconsideration_flag', models.BooleanField(null=True)),
                ('response_assigned_supervisor', models.CharField(max_length=100, null=True)),
                ('response_submitted_by', models.CharField(max_length=100, null=True)),
                ('retrigger_required', models.BooleanField(null=True)),
                ('retrigger_status', models.CharField(max_length=100, null=True)),
                ('row_age', models.IntegerField(null=True)),
                ('signal_close_date', models.DateTimeField(null=True)),
                ('signal_id', models.CharField(max_length=100, null=True)),
                ('signal_propensity', models.FloatField(null=True)),
                ('signalfile_reference', models.CharField(max_length=100, null=True)),
                ('team_name', models.CharField(max_length=100, null=True)),
                ('trigger_age', models.IntegerField(null=True)),
                ('update_screen', models.CharField(max_length=100, null=True)),
                ('use_case', models.CharField(max_length=100, null=True)),
                ('week_begin', models.DateTimeField(null=True)),
                ('lob', models.CharField(max_length=100, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.claims')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.parameter')),
            ],
        ),
    ]
