# Generated by Django 5.1.4 on 2025-01-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='remaining_reserve',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='total_recovery',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='claims',
            name='claim_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claims',
            name='claim_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claims',
            name='general_nature_of_loss',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claims',
            name='loss_claim_cause',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
