# Generated by Django 5.1.4 on 2025-01-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_claims_paid_amount_claims_remaining_reserve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOB',
            fields=[
                ('lob', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('line_of_business', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lob',
            },
        ),
    ]
