# Generated by Django 5.1.4 on 2025-01-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_lob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audit',
            new_name='dsoutcome',
        ),
    ]
