# Generated by Django 5.1.4 on 2025-01-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_rename_audit_dsoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('distribution_channel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'policy',
            },
        ),
    ]
