# Generated by Django 5.1.4 on 2025-01-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'claim_notes',
            },
        ),
    ]
