# Generated by Django 5.1.4 on 2025-01-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_claimnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimnotes',
            name='claim_id',
        ),
        migrations.AddField(
            model_name='claimnotes',
            name='claim',
            field=models.ForeignKey(default='WFI246193292', on_delete=django.db.models.deletion.CASCADE, to='backend_app.claims'),
            preserve_default=False,
        ),
    ]
