# Generated by Django 5.1.4 on 2025-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_remove_claimnotes_claim_id_claimnotes_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimauditable',
            name='final_lob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimauditable',
            name='lob',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
