# Generated by Django 5.1.4 on 2025-01-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_claimauditable_final_lob_claimauditable_lob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimauditable',
            name='parameter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.parameter'),
        ),
    ]
