# Generated by Django 5.1.4 on 2025-01-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_alter_claimauditable_parameter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimauditable',
            old_name='parameter_id',
            new_name='parameter',
        ),
    ]
