# Generated by Django 5.1.4 on 2025-01-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_rename_parameter_id_claimauditable_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoutcome',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsoutcomes', to='backend_app.claims'),
        ),
    ]
