# Generated by Django 5.1.4 on 2025-01-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_alter_dsoutcome_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimauditable',
            name='final_lob',
        ),
        migrations.AddField(
            model_name='claimauditable',
            name='parameter_comments',
            field=models.TextField(null=True),
        ),
    ]
