# Generated by Django 5.1.4 on 2025-01-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_remove_claimauditable_final_lob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimauditable',
            name='final_lob',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
