# Generated by Django 5.1.4 on 2025-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_claimauditable_final_lob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='abcd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
