# Generated by Django 5.1.4 on 2025-01-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_dsoutcome_abcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='finalized_leakage_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
