# Generated by Django 5.1.4 on 2025-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_dsoutcome_finalized_leakage_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsoutcome',
            old_name='finalized_leakage_amount',
            new_name='stored_ds_paid_remaining',
        ),
        migrations.RemoveField(
            model_name='dsoutcome',
            name='abcd',
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_final_leakage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_leakage_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
