# Generated by Django 5.1.4 on 2025-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0018_rename_finalized_leakage_amount_dsoutcome_stored_ds_paid_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_exclusions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
