# Generated by Django 5.1.4 on 2025-01-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0019_dsoutcome_stored_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_leakage_rate_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_leakage_rate_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_leakage_rate_new',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
