# Generated by Django 5.1.4 on 2025-01-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0020_dsoutcome_stored_leakage_rate_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='lob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.lob'),
        ),
    ]
