# Generated by Django 5.1.4 on 2025-01-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0021_alter_claims_lob'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimauditable',
            name='MET',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='claimauditable',
            name='TOTAL',
            field=models.IntegerField(null=True),
        ),
    ]
