# Generated by Django 5.1.4 on 2025-01-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_claimauditable_met_claimauditable_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimauditable',
            name='stored_file_review_score',
            field=models.FloatField(null=True),
        ),
    ]
