# Generated by Django 5.1.4 on 2025-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0023_claimauditable_stored_file_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_matchornot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
