# Generated by Django 5.1.4 on 2025-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_dsoutcome_stored_matchornot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_accurate_signal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_ai_error_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_manual_review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_no_ai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_no_ai_plus_yes_ai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_opp_identified_compliance_review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_opp_identified_compliance_review_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_signal_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='stored_pid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
