# Generated by Django 5.1.4 on 2025-01-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_dsoutcome_stored_accurate_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_duplicate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_is_it_a_potential_leakage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_reported_as_leakage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_sequence_column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_signal_closed_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
