# Generated by Django 5.1.4 on 2025-01-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_dsoutcome_stored_duplicate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsoutcome',
            old_name='stored_signal_closed_date2',
            new_name='stored_signal_close_date2',
        ),
        migrations.AlterField(
            model_name='dsoutcome',
            name='stored_duplicate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
