# Generated by Django 5.1.4 on 2025-01-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_rename_stored_signal_closed_date2_dsoutcome_stored_signal_close_date2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoutcome',
            name='stored_leakage_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
